# Generated by Django 5.1 on 2024-12-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GradeWireapp', '0002_alter_student_mobile_alter_student_parent_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='register_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
