# Generated by Django 5.1 on 2024-12-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GradeWireapp', '0004_alter_student_register_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_id',
            field=models.CharField(max_length=20),
        ),
    ]
