# Generated by Django 5.1 on 2024-12-06 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GradeWireapp', '0006_alter_student_register_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='register_id',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
