# Generated by Django 5.1 on 2025-01-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GradeWireapp', '0007_alter_student_register_id_alter_teacher_teacher_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='mobile',
            field=models.CharField(default='mobile', max_length=10),
        ),
    ]
